<?php

namespace AppBundle\Repository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $workSpaceId
     * @return array
     */
    public function getAllProjects($workSpaceId)
    {
        $q = $this->createQueryBuilder('p')
            ->where('p.workspace = :workSpaceId')
            ->setParameter('workSpaceId', $workSpaceId)
            ->getQuery();
        return $q->getResult();
    }
}
